
CREATE TABLE IF NOT EXISTS FEIRASLIVRES(
    ID         INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LONGITUDE  INT  NOT NULL,
    LATITUDE   INT  NOT NULL,
    SETCENS    BIGINT  NOT NULL,
    AREAP      BIGINT  NOT NULL,
    CODDIST    INTEGER  NOT NULL,
    DISTRITO   VARCHAR(18) NOT NULL,
    CODSUBPREF INTEGER  NOT NULL,
    SUBPREFE   VARCHAR(25) NOT NULL,
    REGIAO5    VARCHAR(6) NOT NULL,
    REGIAO8    VARCHAR(7) NOT NULL,
    NOME_FEIRA VARCHAR(30) NOT NULL,
    REGISTRO   VARCHAR(6) NOT NULL,
    LOGRADOURO VARCHAR(34) NOT NULL,
    NUMERO     VARCHAR(11),
    BAIRRO     VARCHAR(20),
    REFERENCIA VARCHAR(30)
);